# Generated by Django 3.1.1 on 2020-11-05 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(default='null', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type_code', models.CharField(default=3, max_length=1)),
                ('ask', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('favorites', models.ManyToManyField(related_name='favorite', through='home.Fav', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('picture', models.BinaryField(blank=True, editable=True, null=True)),
                ('content_type', models.CharField(blank=True, help_text='The MIMEType of the file', max_length=256, null=True)),
                ('bio', models.TextField()),
                ('github_link', models.URLField(blank=True, default='http://null.html', null=True)),
                ('linkedin_link', models.URLField(blank=True, default='http://null.html', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=300, null=True)),
                ('option_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_access', to='home.forum')),
            ],
        ),
        migrations.CreateModel(
            name='forum_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_forum', models.CharField(blank=True, max_length=50, null=True)),
                ('tags_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_access', to='home.forum')),
            ],
        ),
        migrations.AddField(
            model_name='fav',
            name='forum_fav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.forum'),
        ),
        migrations.AddField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.CharField(max_length=1000)),
                ('single', models.CharField(blank=True, max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discuss_access', to='home.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anshumc', to='home.forum')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vivekmc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userprofile', 'answer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('forum_fav', 'user')},
        ),
    ]
