# Generated by Django 2.2.7 on 2020-09-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_tags',
            name='tags_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_access', to='home.forum'),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_access', to='home.forum'),
        ),
    ]
