# Generated by Django 2.2.7 on 2020-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200919_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_tags',
            name='tags_forum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
