# Generated by Django 2.2.7 on 2020-09-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200919_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='ask',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
