# Generated by Django 2.2.7 on 2020-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200920_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
